FROM node:8

RUN mkdir -p /usr/src/app

COPY . /usr/src/app

WORKDIR /usr/src/app/client
RUN npm install
RUN npm run build:prod

WORKDIR /usr/src/app/server
RUN npm install
RUN npm run build:prod

EXPOSE 3000
# EXPOSE 8443

CMD [ "npm", "run", "start" ]
