version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    restart: "always"
  web:
    build:
       context: .
       dockerfile: Dockerfile.prod
    links:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    restart: "always"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/usr/src/app/uploads
